/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.AsrCancel
import cn.hedgeho9.murmur.api.models.AsrFinish
import cn.hedgeho9.murmur.api.models.AsrStart

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * 
 *
 */
@Serializable(with = AsrClientEventSerializer::class)
sealed interface AsrClientEvent {
    @JvmInline
     value class CancelWrapper(val value: AsrCancel) : AsrClientEvent

    @JvmInline
     value class FinishWrapper(val value: AsrFinish) : AsrClientEvent

    @JvmInline
     value class StartWrapper(val value: AsrStart) : AsrClientEvent

}

object AsrClientEventSerializer : KSerializer<AsrClientEvent> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("AsrClientEvent")

    override fun serialize(encoder: Encoder, value: AsrClientEvent) {
        require(encoder is JsonEncoder)
        val jsonObject = when (value) {
            is AsrClientEvent.CancelWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrCancel.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("cancel")
                JsonObject(jsonMap)
            }
            is AsrClientEvent.FinishWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrFinish.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("finish")
                JsonObject(jsonMap)
            }
            is AsrClientEvent.StartWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrStart.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("start")
                JsonObject(jsonMap)
            }
        }
        encoder.encodeJsonElement(jsonObject)
    }

    override fun deserialize(decoder: Decoder): AsrClientEvent {
        require(decoder is JsonDecoder)
        val element = decoder.decodeJsonElement().jsonObject

        val discriminatorValue = element["type"]?.jsonPrimitive?.content
            ?: throw SerializationException("Missing type field")

        return when (discriminatorValue) {
            "cancel" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrCancel.serializer(), element)
                AsrClientEvent.CancelWrapper(decoded)
            }
            "finish" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrFinish.serializer(), element)
                AsrClientEvent.FinishWrapper(decoded)
            }
            "start" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrStart.serializer(), element)
                AsrClientEvent.StartWrapper(decoded)
            }
            else -> throw SerializationException("Unknown AsrClientEvent type: $discriminatorValue")
        }
    }
}

