/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param endpoint 
 * @param model 
 * @param token 
 * @param expiresAt 
 */
@Serializable

data class AsrCredentials (

    @SerialName(value = "endpoint")
    val endpoint: kotlin.String,

    @SerialName(value = "model")
    val model: kotlin.String,

    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "expires_at")
    val expiresAt: kotlin.Int

) {


}

