/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param code 
 * @param message 
 */
@Serializable

data class AsrError (

    @SerialName(value = "type")
    val type: AsrError.Type,

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "message")
    val message: kotlin.String

) {

    /**
     * 
     *
     * Values: error
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "error") error("error");
    }

}

