/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.AsrCompleted
import cn.hedgeho9.murmur.api.models.AsrError
import cn.hedgeho9.murmur.api.models.AsrReady
import cn.hedgeho9.murmur.api.models.AsrTranscript

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * 
 *
 */
@Serializable(with = AsrServerEventSerializer::class)
sealed interface AsrServerEvent {
    @JvmInline
     value class CompletedWrapper(val value: AsrCompleted) : AsrServerEvent

    @JvmInline
     value class ErrorWrapper(val value: AsrError) : AsrServerEvent

    @JvmInline
     value class ReadyWrapper(val value: AsrReady) : AsrServerEvent

    @JvmInline
     value class TranscriptWrapper(val value: AsrTranscript) : AsrServerEvent

}

object AsrServerEventSerializer : KSerializer<AsrServerEvent> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("AsrServerEvent")

    override fun serialize(encoder: Encoder, value: AsrServerEvent) {
        require(encoder is JsonEncoder)
        val jsonObject = when (value) {
            is AsrServerEvent.CompletedWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrCompleted.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("completed")
                JsonObject(jsonMap)
            }
            is AsrServerEvent.ErrorWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrError.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("error")
                JsonObject(jsonMap)
            }
            is AsrServerEvent.ReadyWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrReady.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("ready")
                JsonObject(jsonMap)
            }
            is AsrServerEvent.TranscriptWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AsrTranscript.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("transcript")
                JsonObject(jsonMap)
            }
        }
        encoder.encodeJsonElement(jsonObject)
    }

    override fun deserialize(decoder: Decoder): AsrServerEvent {
        require(decoder is JsonDecoder)
        val element = decoder.decodeJsonElement().jsonObject

        val discriminatorValue = element["type"]?.jsonPrimitive?.content
            ?: throw SerializationException("Missing type field")

        return when (discriminatorValue) {
            "completed" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrCompleted.serializer(), element)
                AsrServerEvent.CompletedWrapper(decoded)
            }
            "error" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrError.serializer(), element)
                AsrServerEvent.ErrorWrapper(decoded)
            }
            "ready" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrReady.serializer(), element)
                AsrServerEvent.ReadyWrapper(decoded)
            }
            "transcript" -> {
                val decoded = decoder.json.decodeFromJsonElement(AsrTranscript.serializer(), element)
                AsrServerEvent.TranscriptWrapper(decoded)
            }
            else -> throw SerializationException("Unknown AsrServerEvent type: $discriminatorValue")
        }
    }
}

