/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param format 
 * @param sampleRate 
 * @param channels 
 */
@Serializable

data class AsrStart (

    @SerialName(value = "type")
    val type: AsrStart.Type,

    @SerialName(value = "format")
    val format: AsrStart.Format,

    @SerialName(value = "sample_rate")
    val sampleRate: kotlin.Int,

    @SerialName(value = "channels")
    val channels: kotlin.Int

) {

    /**
     * 
     *
     * Values: start
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "start") start("start");
    }
    /**
     * 
     *
     * Values: pcm_s16le
     */
    @Serializable
    enum class Format(val value: kotlin.String) {
        @SerialName(value = "pcm_s16le") pcm_s16le("pcm_s16le");
    }

}

