/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param segmentId 
 * @param text 
 * @param isFinal 
 */
@Serializable

data class AsrTranscript (

    @SerialName(value = "type")
    val type: AsrTranscript.Type,

    @SerialName(value = "segment_id")
    val segmentId: kotlin.String,

    @SerialName(value = "text")
    val text: kotlin.String,

    @SerialName(value = "is_final")
    val isFinal: kotlin.Boolean

) {

    /**
     * 
     *
     * Values: transcript
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "transcript") transcript("transcript");
    }

}

