/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.AssistantContentPartsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param parts 
 * @param finishReason 
 */
@Serializable

data class AssistantContent (

    @SerialName(value = "parts")
    val parts: kotlin.collections.List<AssistantContentPartsInner>,

    @SerialName(value = "finish_reason")
    val finishReason: AssistantContent.FinishReason

) {

    /**
     * 
     *
     * Values: stop,tool_call,interrupted,error
     */
    @Serializable
    enum class FinishReason(val value: kotlin.String) {
        @SerialName(value = "stop") stop("stop"),
        @SerialName(value = "tool_call") tool_call("tool_call"),
        @SerialName(value = "interrupted") interrupted("interrupted"),
        @SerialName(value = "error") error("error");
    }

}

