/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.UserContent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 客户端创建草稿时生成并保存的 UUIDv7，重试复用；重复创建返回 409。
 * @param content 
 * @param title 
 */
@Serializable

data class CreatePostRequest (

    /* 客户端创建草稿时生成并保存的 UUIDv7，重试复用；重复创建返回 409。 */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "content")
    val content: UserContent,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

