/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param expiresIn 
 */
@Serializable

data class ImageUrl (

    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    @SerialName(value = "expires_in")
    val expiresIn: kotlin.Int

) {


}

