/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class Post (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "title")
    val title: kotlin.String?,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String

) {


}

