/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.TagSuggestion

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 */
@Serializable

data class TagSuggestions (

    @SerialName(value = "items")
    val items: kotlin.collections.List<TagSuggestion>

) {


}

