/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param text 
 */
@Serializable

data class TextPart (

    @SerialName(value = "type")
    val type: TextPart.Type,

    @SerialName(value = "text")
    val text: kotlin.String

) {

    /**
     * 
     *
     * Values: text
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "text") text("text");
    }

}

