/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.ToolContent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param postId 
 * @param turnId 
 * @param createdAt 
 * @param role 
 * @param content 
 * @param toolCallId 
 */
@Serializable

data class ToolMessage (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "post_id")
    val postId: java.util.UUID,

    @Contextual @SerialName(value = "turn_id")
    val turnId: java.util.UUID,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "role")
    val role: ToolMessage.Role,

    @SerialName(value = "content")
    val content: ToolContent,

    @SerialName(value = "tool_call_id")
    val toolCallId: kotlin.String

) {

    /**
     * 
     *
     * Values: tool
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "tool") tool("tool");
    }

}

