/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param id 
 * @param name 
 * @param arguments 
 */
@Serializable

data class ToolCallPart (

    @SerialName(value = "type")
    val type: ToolCallPart.Type,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "arguments")
    val arguments: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>

) {

    /**
     * 
     *
     * Values: tool_call
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "tool_call") tool_call("tool_call");
    }

}

