/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param contentType 
 * @param sizeBytes 
 */
@Serializable

data class UploadRequest (

    @SerialName(value = "content_type")
    val contentType: UploadRequest.ContentType,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Int

) {

    /**
     * 
     *
     * Values: imageSlashJpeg,imageSlashPng,imageSlashWebp
     */
    @Serializable
    enum class ContentType(val value: kotlin.String) {
        @SerialName(value = "image/jpeg") imageSlashJpeg("image/jpeg"),
        @SerialName(value = "image/png") imageSlashPng("image/png"),
        @SerialName(value = "image/webp") imageSlashWebp("image/webp");
    }

}

