/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.Image

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param image 
 * @param uploadUrl 
 * @param expiresIn 
 */
@Serializable

data class UploadResponse (

    @SerialName(value = "image")
    val image: Image,

    @Contextual @SerialName(value = "upload_url")
    val uploadUrl: java.net.URI,

    @SerialName(value = "expires_in")
    val expiresIn: kotlin.Int

) {


}

