/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.murmur.api.models

import cn.hedgeho9.murmur.api.models.ImagePart
import cn.hedgeho9.murmur.api.models.TextPart

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * 
 *
 */
@Serializable(with = UserContentPartsInnerSerializer::class)
sealed interface UserContentPartsInner {
    @JvmInline
     value class ImageWrapper(val value: ImagePart) : UserContentPartsInner

    @JvmInline
     value class TextWrapper(val value: TextPart) : UserContentPartsInner

}

object UserContentPartsInnerSerializer : KSerializer<UserContentPartsInner> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("UserContentPartsInner")

    override fun serialize(encoder: Encoder, value: UserContentPartsInner) {
        require(encoder is JsonEncoder)
        val jsonObject = when (value) {
            is UserContentPartsInner.ImageWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(ImagePart.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("image")
                JsonObject(jsonMap)
            }
            is UserContentPartsInner.TextWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(TextPart.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("text")
                JsonObject(jsonMap)
            }
        }
        encoder.encodeJsonElement(jsonObject)
    }

    override fun deserialize(decoder: Decoder): UserContentPartsInner {
        require(decoder is JsonDecoder)
        val element = decoder.decodeJsonElement().jsonObject

        val discriminatorValue = element["type"]?.jsonPrimitive?.content
            ?: throw SerializationException("Missing type field")

        return when (discriminatorValue) {
            "image" -> {
                val decoded = decoder.json.decodeFromJsonElement(ImagePart.serializer(), element)
                UserContentPartsInner.ImageWrapper(decoded)
            }
            "text" -> {
                val decoded = decoder.json.decodeFromJsonElement(TextPart.serializer(), element)
                UserContentPartsInner.TextWrapper(decoded)
            }
            else -> throw SerializationException("Unknown UserContentPartsInner type: $discriminatorValue")
        }
    }
}

