/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param imageId 
 */
@Serializable

data class ImagePart (

    @SerialName(value = "type")
    val type: ImagePart.Type,

    @Contextual @SerialName(value = "image_id")
    val imageId: java.util.UUID

) {

    /**
     * 
     *
     * Values: image
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "image") image("image");
    }

}

