/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param contentType 
 * @param sizeBytes 
 * @param width 
 * @param height 
 * @param status 
 * @param createdAt 
 */
@Serializable

data class Image (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Int,

    @SerialName(value = "width")
    val width: kotlin.Int?,

    @SerialName(value = "height")
    val height: kotlin.Int?,

    @SerialName(value = "status")
    val status: Image.Status,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String

) {

    /**
     * 
     *
     * Values: pending,ready
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "ready") ready("ready");
    }

}

