/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param `data` Any JSON value
 */
@Serializable

data class JsonPart (

    @SerialName(value = "type")
    val type: JsonPart.Type,

    /* Any JSON value */
    @Contextual @SerialName(value = "data")
    val `data`: kotlinx.serialization.json.JsonElement?

) {

    /**
     * 
     *
     * Values: json
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "json") json("json");
    }

}

