/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models

import cn.hedgeho9.myapp.api.models.Post

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 * @param nextCursor 
 */
@Serializable

data class PostPage (

    @SerialName(value = "items")
    val items: kotlin.collections.List<Post>,

    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String?

) {


}

