/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models

import cn.hedgeho9.myapp.api.models.Message
import cn.hedgeho9.myapp.api.models.Post

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param post 
 * @param messages 
 */
@Serializable

data class PostDetail (

    @SerialName(value = "post")
    val post: Post,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<Message>

) {


}

