/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models

import cn.hedgeho9.myapp.api.models.ImagePart
import cn.hedgeho9.myapp.api.models.JsonPart
import cn.hedgeho9.myapp.api.models.TextPart

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * 
 *
 */
@Serializable(with = ToolContentPartsInnerSerializer::class)
sealed interface ToolContentPartsInner {
    @JvmInline
     value class ImageWrapper(val value: ImagePart) : ToolContentPartsInner

    @JvmInline
     value class JsonWrapper(val value: JsonPart) : ToolContentPartsInner

    @JvmInline
     value class TextWrapper(val value: TextPart) : ToolContentPartsInner

}

object ToolContentPartsInnerSerializer : KSerializer<ToolContentPartsInner> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("ToolContentPartsInner")

    override fun serialize(encoder: Encoder, value: ToolContentPartsInner) {
        require(encoder is JsonEncoder)
        val jsonObject = when (value) {
            is ToolContentPartsInner.ImageWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(ImagePart.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("image")
                JsonObject(jsonMap)
            }
            is ToolContentPartsInner.JsonWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(JsonPart.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("json")
                JsonObject(jsonMap)
            }
            is ToolContentPartsInner.TextWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(TextPart.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["type"] = JsonPrimitive("text")
                JsonObject(jsonMap)
            }
        }
        encoder.encodeJsonElement(jsonObject)
    }

    override fun deserialize(decoder: Decoder): ToolContentPartsInner {
        require(decoder is JsonDecoder)
        val element = decoder.decodeJsonElement().jsonObject

        val discriminatorValue = element["type"]?.jsonPrimitive?.content
            ?: throw SerializationException("Missing type field")

        return when (discriminatorValue) {
            "image" -> {
                val decoded = decoder.json.decodeFromJsonElement(ImagePart.serializer(), element)
                ToolContentPartsInner.ImageWrapper(decoded)
            }
            "json" -> {
                val decoded = decoder.json.decodeFromJsonElement(JsonPart.serializer(), element)
                ToolContentPartsInner.JsonWrapper(decoded)
            }
            "text" -> {
                val decoded = decoder.json.decodeFromJsonElement(TextPart.serializer(), element)
                ToolContentPartsInner.TextWrapper(decoded)
            }
            else -> throw SerializationException("Unknown ToolContentPartsInner type: $discriminatorValue")
        }
    }
}

