/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models

import cn.hedgeho9.myapp.api.models.UserContent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param postId 
 * @param turnId 
 * @param createdAt 
 * @param role 
 * @param content 
 * @param toolCallId 
 */
@Serializable

data class UserMessage (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "post_id")
    val postId: java.util.UUID,

    @Contextual @SerialName(value = "turn_id")
    val turnId: java.util.UUID,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "role")
    val role: UserMessage.Role,

    @SerialName(value = "content")
    val content: UserContent,

    @Contextual @SerialName(value = "tool_call_id")
    val toolCallId: kotlinx.serialization.json.JsonElement?

) {

    /**
     * 
     *
     * Values: user
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "user") user("user");
    }

}

