/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models

import cn.hedgeho9.myapp.api.models.AssistantMessage
import cn.hedgeho9.myapp.api.models.ToolContent
import cn.hedgeho9.myapp.api.models.ToolMessage
import cn.hedgeho9.myapp.api.models.UserMessage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * 
 *
 */
@Serializable(with = MessageSerializer::class)
sealed interface Message {
    @JvmInline
     value class AssistantWrapper(val value: AssistantMessage) : Message

    @JvmInline
     value class ToolWrapper(val value: ToolMessage) : Message

    @JvmInline
     value class UserWrapper(val value: UserMessage) : Message

}

object MessageSerializer : KSerializer<Message> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("Message")

    override fun serialize(encoder: Encoder, value: Message) {
        require(encoder is JsonEncoder)
        val jsonObject = when (value) {
            is Message.AssistantWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(AssistantMessage.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["role"] = JsonPrimitive("assistant")
                JsonObject(jsonMap)
            }
            is Message.ToolWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(ToolMessage.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["role"] = JsonPrimitive("tool")
                JsonObject(jsonMap)
            }
            is Message.UserWrapper -> {
                val jsonMap = encoder.json.encodeToJsonElement(UserMessage.serializer(), value.value).jsonObject.toMutableMap()
                jsonMap["role"] = JsonPrimitive("user")
                JsonObject(jsonMap)
            }
        }
        encoder.encodeJsonElement(jsonObject)
    }

    override fun deserialize(decoder: Decoder): Message {
        require(decoder is JsonDecoder)
        val element = decoder.decodeJsonElement().jsonObject

        val discriminatorValue = element["role"]?.jsonPrimitive?.content
            ?: throw SerializationException("Missing role field")

        return when (discriminatorValue) {
            "assistant" -> {
                val decoded = decoder.json.decodeFromJsonElement(AssistantMessage.serializer(), element)
                Message.AssistantWrapper(decoded)
            }
            "tool" -> {
                val decoded = decoder.json.decodeFromJsonElement(ToolMessage.serializer(), element)
                Message.ToolWrapper(decoded)
            }
            "user" -> {
                val decoded = decoder.json.decodeFromJsonElement(UserMessage.serializer(), element)
                Message.UserWrapper(decoded)
            }
            else -> throw SerializationException("Unknown Message role: $discriminatorValue")
        }
    }
}

