/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cn.hedgeho9.myapp.api.models

import cn.hedgeho9.myapp.api.models.UserContentPartsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param parts 
 */
@Serializable

data class UserContent (

    @SerialName(value = "parts")
    val parts: kotlin.collections.List<UserContentPartsInner>

) {


}

